build: off
shallow_clone: false
platform: 'x64'
clone_folder: c:\projects\ldaptools

environment:
  matrix:
    - PHP_VERSION: "5.6.17"
    - PHP_VERSION: "7.0.9"
    - PHP_VERSION: "7.1.1"

matrix:
  allow_failures:
    - PHP_VERSION: "5.6.17"

install:
  - ps: Set-Service wuauserv -StartupType "Automatic"; Start-Service wuauserv
  - ps: appveyor-retry cinst --ignore-checksums -y php --version $Env:PHP_VERSION
  - SET PATH=C:\tools\php\;%PATH%
  - cd c:\tools\php
  - copy php.ini-development php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_ldap.dll >> php.ini
  - cd C:\projects\ldaptools
  - php -r "readfile('https://getcomposer.org/installer');" | php

before_test:
  - cd C:\projects\ldaptools
  - php composer.phar install --no-interaction --no-progress --optimize-autoloader --prefer-source --no-ansi

test_script:
  - cd C:\projects\ldaptools
  - bin\phpspec.bat run
